name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: release_please
        uses: googleapis/release-please-action@v4
      - uses: goreleaser/goreleaser-action@v6
        if: ${{ steps.release_please.outputs.release_created }}
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
